### ISSUE TITLE
Explicitly specify the text color for Account component and wallet connect modal

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-react-frontend-template#18] opened 2024-01-20 08:09 UTC
Currently, the text color for the Account component and the wallet connect modal is not specified and sometimes the text automatically becomes white.

Example:
<img width="933" alt="image" src="https://github.com/algorandfoundation/algokit-react-frontend-template/assets/52557585/428748f3-e3ff-4bc9-9fb8-46f7122463d1">

Solution:
add explicit text color `text-gray-900`

**Comment by aorumbayev** [comment] 2024-01-20 16:34
@iskysun96 can you provide a codesanbox or repo sample with steps to replicate the case when default component has white labeled color.

**Comment by iskysun96** [comment] 2024-01-21 00:50
try running a localhost of this commit: https://github.com/iskysun96/blockchain-photo-diary/commit/6967cc00a6c08b7e95d9e23fe14e0e386695fa05

**Comment by aorumbayev** [comment] 2024-01-22 12:12
@iskysun96 the issue on that particular commit was due to explicit definition of text-white on a div wrapping your entire navbar. By default starter instance of the template does not enforce any particular fixed colors, you can switch in between daisy ui themes as needed or set appropriate colors depending on how you are further extending the starter template. Hence, closing issue as its not a bug in the template

**Closed by aorumbayev** 2024-01-22 12:12 UTC
